# Create mesh file for Ariane

Need to create variable that exists in NEMO 3.6 --- gdept_0. Dimensions: (t,z,y,x)

In [78]:
import matplotlib.pyplot as plt
import netCDF4 as nc
import numpy as np

from salishsea_tools import (
    nc_tools,
    viz_tools,
)

%matplotlib inline

In [79]:
folder = './'
file1 = '../ANHA12_mesh_zgr12.nc'
file2 = '../ANHA12_mesh_hgr10.nc'
mask = nc.Dataset('/ocean/brogalla/GEOTRACES/data/ANHA12_mask.nc')
mesh_zgr = nc.Dataset(file1)
mesh_hgr = nc.Dataset(file2)

In [80]:
mesh_zgr

<class 'netCDF4._netCDF4.Dataset'>
root group (NETCDF4 data model, file format HDF5):
    Conventions: CF-1.6
    title: ANHA12 mesh_zgr
    institution: Dept of Earth, Ocean & Atmospheric Sciences, University of British Columbia
    source: https://bitbucket.org/ccar-modeling/analysis-birgit/src/tip/notebooks/ANHA12/create_meshmask.ipynb
    references: REQUIRED
    history: [2018-03-29 13:53:58] Created netCDF4 zlib=True dataset.
    comment: Edited ANHA12 mesh_zgr file
    dimensions(sizes): x(1632), y(2400), z(50), t(1)
    variables(dimensions): float32 nav_lat(y,x), float32 nav_lon(y,x), float32 nav_lev(z), float64 time_counter(t), int16 mbathy(t,y,x), float32 hdept(t,y,x), float32 hdepw(t,y,x), float64 gdept_1d(t,z), float64 gdepw_1d(t,z), float64 e3t_1d(t,z), float64 e3w_1d(t,z), int8 tmask(t,z,y,x), float32 e3t_0(t,z,y,x), float32 e3u_0(t,z,y,x), float32 e3v_0(t,z,y,x), float32 e3w_0(t,z,y,x)
    groups: 

In [81]:
hdepw = mesh_zgr.variables['hdepw']
tmask = mesh_zgr.variables['tmask']
mbathy = mesh_zgr.variables['mbathy']
e3w_1d = mesh_zgr.variables['e3w_1d']
gdepw_1d = mesh_zgr.variables['gdepw_1d']
e3w_0 = mesh_zgr.variables['e3w_0']
e3t_0 = mesh_zgr.variables['e3t_0']
glamt = mesh_hgr.variables['glamt']
glamu = mesh_hgr.variables['glamu']
gphit = mesh_hgr.variables['gphit']
gphiv = mesh_hgr.variables['gphiv']
e1t = mesh_hgr.variables['e1t']
e1v = mesh_hgr.variables['e1v']
e2t = mesh_hgr.variables['e2t']
e2u = mesh_hgr.variables['e2u']

In [110]:
hdepw = np.array(hdepw)
tmask = np.array(tmask)
mbathy = np.array(mbathy)
e3w_1d = np.array(e3w_1d)
gdepw_1d = np.array(gdepw_1d)
e3w_0 = np.array(e3w_0)
e3t_0 = np.array(e3t_0)
glamt = np.array(glamt)
glamu = np.array(glamu)
gphit = np.array(gphit)
gphiv = np.array(gphiv)
e1t = np.array(e1t)
e1v = np.array(e1v)
e2t = np.array(e2t)
e2u = np.array(e2u)

Compare with Susan's meshmask file variables:

In [82]:
meshmask_susan = nc.Dataset('/ocean/brogalla/GEOTRACES/Ariane/mesh_mask201702.nc')

In [83]:
meshmask_susan

<class 'netCDF4._netCDF4.Dataset'>
root group (NETCDF4 data model, file format HDF5):
    file_name: mesh_mask.nc
    TimeStamp: 30/09/2017 16:10:02 -0700
    dimensions(sizes): x(398), y(898), z(40), t(1)
    variables(dimensions): float32 nav_lon(y,x), float32 nav_lat(y,x), float32 nav_lev(z), float64 time_counter(t), int8 tmask(t,z,y,x), int8 umask(t,z,y,x), int8 vmask(t,z,y,x), int8 fmask(t,z,y,x), int8 tmaskutil(t,y,x), int8 umaskutil(t,y,x), int8 vmaskutil(t,y,x), int8 fmaskutil(t,y,x), float32 glamt(t,y,x), float32 glamu(t,y,x), float32 glamv(t,y,x), float32 glamf(t,y,x), float32 gphit(t,y,x), float32 gphiu(t,y,x), float32 gphiv(t,y,x), float32 gphif(t,y,x), float64 e1t(t,y,x), float64 e1u(t,y,x), float64 e1v(t,y,x), float64 e1f(t,y,x), float64 e2t(t,y,x), float64 e2u(t,y,x), float64 e2v(t,y,x), float64 e2f(t,y,x), float64 ff(t,y,x), int16 mbathy(t,y,x), int16 misf(t,y,x), float32 isfdraft(t,y,x), float64 e3t_0(t,z,y,x), float64 e3u_0(t,z,y,x), float64 e3v_0(t,z,y,x), float64 e3

In [84]:
s_gdepw_0 = meshmask_susan.variables['gdepw_0']
s_e3w_0 = meshmask_susan.variables['e3w_0']
s_mbathy = meshmask_susan.variables['mbathy']
s_gdepw_1d = meshmask_susan.variables['gdepw_1d']

In [85]:
print(s_gdepw_0.shape)
print(s_e3w_0.shape)
print(s_mbathy.shape)
print(s_gdepw_1d.shape)

(1, 40, 898, 398)
(1, 40, 898, 398)
(1, 898, 398)
(1, 40)


In [86]:
s_gdepw_0 = np.array(s_gdepw_0)
s_e3w_0 = np.array(s_e3w_0)
s_mbathy = np.array(s_mbathy)
s_gdepw_1d = np.array(s_gdepw_1d)

In [87]:
np.array_equal(s_e3w_0, s_gdepw_0)

False

In [88]:
print(np.amax(s_gdepw_0))
print(np.amax(s_e3w_0))
print(np.amax(s_mbathy))
print(np.amax(s_gdepw_1d))

428.0
26.9320432476
39
428.0


In [89]:
s_gdepw_1d

array([[   0.        ,    1.00000123,    2.00000639,    3.00001921,
           4.00004695,    5.00010374,    6.00021712,    7.00044072,
           8.00087898,    9.00173537,   10.00340608,   11.00666275,
          12.01300785,   13.02536622,   14.04942854,   15.09625559,
          16.18730348,   17.36403385,   18.7059723 ,   20.36347338,
          22.61306387,   25.93741305,   31.10103509,   39.1188566 ,
          50.96323669,   67.05207424,   86.96747037,  109.73706598,
         134.34593444,  160.02956159,  186.30527815,  212.89655735,
         239.65304462,  266.49521437,  293.38160496,  320.29076029,
         347.21161956,  374.1384921 ,  401.06845307,  428.        ]])

In [90]:
s_mbathy[0,1,131]

8

In [91]:
s_gdepw_0[0,:,1,131]

array([   0.        ,    1.00000119,    2.00000644,    3.00001931,
          4.00004673,    5.00010395,    6.00021696,    7.0004406 ,
          8.00087929,    9.00173569,   10.00340652,   11.00666237,
         12.01300812,   13.02536583,   14.04942894,   15.0962553 ,
         16.18730354,   17.36403465,   18.70597267,   20.36347389,
         22.61306381,   25.93741226,   31.10103416,   39.11885834,
         50.96323776,   67.05207062,   86.96746826,  109.73706818,
        134.34593201,  160.02955627,  186.30528259,  212.89656067,
        239.65304565,  266.49520874,  293.3815918 ,  320.29077148,
        347.21160889,  374.13848877,  401.06845093,  428.        ], dtype=float32)

In [92]:
s_gdepw_0[0,:,0,0]

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.], dtype=float32)

Create new gdepw_0 for ANHA12:

In [94]:
print(hdepw.shape)
print(e3w_0.shape)
print(mbathy.shape)
print(gdepw_1d.shape)
print(e3w_1d.shape)

(1, 2400, 1632)
(1, 50, 2400, 1632)
(1, 2400, 1632)
(1, 50)
(1, 50)


In [95]:
print(np.amax(hdepw))
print(np.amax(e3w_0))
print(np.amax(mbathy))
print(np.amax(gdepw_1d))
print(np.amax(e3w_1d))

5750.0
697.526
49
5500.00159104
453.200849538


In [96]:
e3w_0[0,:,0,864]

array([   1.00036931,    1.04692233,    1.10377085,    1.17318881,
          1.25795054,    1.36144078,    1.48778749,    1.64202332,
          1.8302815 ,    2.06003332,    2.34037328,    2.68236566,
          3.09945679,    3.60797167,    4.22770262,    4.98260689,
          5.90162373,    7.01962519,    8.3785038 ,   10.02840137,
         12.02905178,   14.45122623,   17.37817764,   20.9070034 ,
         25.14973068,   30.23387527,   36.30212021,   43.51065826,
         52.0256424 ,   62.01715088,   73.65010071,   87.0717392 ,
        102.39587402,  119.6844635 ,  138.92852783,  160.03088379,
        182.79438782,  206.91926575,  232.01235962,  257.60900879,
        283.20562744,  308.29873657,  332.4236145 ,  355.18710327,
        376.28945923,  395.53353882,  412.82211304,  428.14627075,
        473.73760986,  512.81756592], dtype=float32)

In [97]:
e3w_0[0,:,1428,539]

array([   1.00036931,    1.04692233,    1.10377085,    1.17318881,
          1.25795054,    1.36144078,    1.48778749,    1.64202332,
          1.8302815 ,    2.06003332,    2.34037328,    2.68236566,
          3.09945679,    3.60797167,    4.22770262,    4.98260689,
          5.90162373,    7.01962519,    8.3785038 ,   10.02840137,
         12.02905178,   14.45122623,   17.37817764,   16.9126873 ,
         14.16931438,   30.23387527,   36.30212021,   43.51065826,
         52.0256424 ,   62.01715088,   73.65010071,   87.0717392 ,
        102.39587402,  119.6844635 ,  138.92852783,  160.03088379,
        182.79438782,  206.91926575,  232.01235962,  257.60900879,
        283.20562744,  308.29873657,  332.4236145 ,  355.18710327,
        376.28945923,  395.53353882,  412.82211304,  428.14627075,
        441.56790161,  453.20083618], dtype=float32)

In [98]:
e3w_0[0,:,0,0]

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.], dtype=float32)

In [99]:
np.cumsum(e3w_0[0,:,1428,539])

array([  1.00036931e+00,   2.04729176e+00,   3.15106249e+00,
         4.32425117e+00,   5.58220196e+00,   6.94364262e+00,
         8.43142986e+00,   1.00734529e+01,   1.19037342e+01,
         1.39637680e+01,   1.63041420e+01,   1.89865074e+01,
         2.20859642e+01,   2.56939354e+01,   2.99216385e+01,
         3.49042435e+01,   4.08058662e+01,   4.78254929e+01,
         5.62039948e+01,   6.62323990e+01,   7.82614517e+01,
         9.27126770e+01,   1.10090851e+02,   1.27003540e+02,
         1.41172852e+02,   1.71406723e+02,   2.07708847e+02,
         2.51219513e+02,   3.03245148e+02,   3.65262299e+02,
         4.38912415e+02,   5.25984131e+02,   6.28380005e+02,
         7.48064453e+02,   8.86992981e+02,   1.04702393e+03,
         1.22981836e+03,   1.43673767e+03,   1.66875000e+03,
         1.92635901e+03,   2.20956470e+03,   2.51786353e+03,
         2.85028711e+03,   3.20547412e+03,   3.58176367e+03,
         3.97729712e+03,   4.39011914e+03,   4.81826562e+03,
         5.25983350e+03,

In [100]:
a = np.cumsum(e3w_0[0,:,:,:],axis=0)
print(a.shape)

(50, 2400, 1632)


In [101]:
print(np.amin(a))
print(np.amax(a))

0.0
6095.61


Check that points on land are still zeros:

In [102]:
a[:,0,0]

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.], dtype=float32)

In [103]:
b = np.reshape(a,(1,50,2400,1632))
print(b.shape)

(1, 50, 2400, 1632)


Check tmask at initial position coordinates: [1428,539], [1411,539], [1399,537]

In [118]:
tmask.shape

(1, 50, 2400, 1632)

In [119]:
tmask[0,:,1428,539]

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0], dtype=int8)

In [120]:
tmask[0,:,539,1428]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0], dtype=int8)

In [121]:
tmask[0,:,1411,539]

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0], dtype=int8)

In [122]:
tmask[0,:,539,1411]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0], dtype=int8)

In [123]:
tmask[0,:,1399,537]

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0], dtype=int8)

In [124]:
tmask[0,:,537,1399]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0], dtype=int8)

## Create NetCDF file:

In [111]:
# Load structure from sample dataset:
lat = mesh_zgr.variables['nav_lat']
lon = mesh_zgr.variables['nav_lon']
BX = mesh_zgr.dimensions['x']
BY = mesh_zgr.dimensions['y']
BZ = mesh_zgr.dimensions['z']
t = mesh_zgr.dimensions['t']

In [115]:
# Setup the new NetCDF file:
ncd = nc.Dataset('ANHA12_Ariane_mesh.nc', 'w', zlib=True)
nc_tools.init_dataset_attrs(
    ncd,
    title='ANHA12 mesh',
    notebook_name='mesh',
    nc_filepath='./mesh.nc',
    comment='Edited ANHA12 mesh file')

ncd.createDimension('x',len(BX))
ncd.createDimension('y',len(BY))
ncd.createDimension('z',len(BZ))
ncd.createDimension('t',None)

file format: NETCDF4
Conventions: CF-1.6
title: ANHA12 mesh
institution: Dept of Earth, Ocean & Atmospheric Sciences, University of British Columbia
source: https://bitbucket.org/ccar-modeling/analysis-birgit/src/tip/notebooks/ANHA12/Ariane/mesh.ipynb
references: REQUIRED
history: [2018-08-08 10:48:19] Created netCDF4 zlib=True dataset.
comment: Edited ANHA12 mesh file


<class 'netCDF4._netCDF4.Dimension'> (unlimited): name = 't', size = 0

In [116]:
gdepw_0_var = ncd.createVariable('gdepw_0', 'float32', ('t','z','y','x'))
gdepw_0_var.units = 'gdepw_0'
gdepw_0_var.long_name = 'gdepw_0'
gdepw_0_var[:] = b

tmask_var = ncd.createVariable('tmask', 'int8', ('t', 'z','y','x'))
tmask_var.units = 'tmask'
tmask_var.long_name = 'tmask'
tmask_var[:] = tmask

e3t_0_var = ncd.createVariable('e3t_0', 'float32', ('t','z','y','x'))
e3t_0_var.units = 'e3t_0'
e3t_0_var.long_name = 'e3t_0'
e3t_0_var[:] = e3t_0

glamt_var = ncd.createVariable('glamt', 'float32', ('t','y','x'))
glamt_var.units = 'glamt'
glamt_var.long_name = 'glamt'
glamt_var[:] = glamt

glamu_var = ncd.createVariable('glamu', 'float32', ('t','y','x'))
glamu_var.units = 'glamu'
glamu_var.long_name = 'glamu'
glamu_var[:] = glamu

gphit_var = ncd.createVariable('gphit', 'float32', ('t','y','x'))
gphit_var.units = 'gphit'
gphit_var.long_name = 'gphit'
gphit_var[:] = gphit

gphiv_var = ncd.createVariable('gphiv', 'float32', ('t', 'y','x'))
gphiv_var.units = 'gphiv'
gphiv_var.long_name = 'gphiv'
gphiv_var[:] = gphiv

e1t_var = ncd.createVariable('e1t', 'float64', ('t', 'y','x'))
e1t_var.units = 'e1t'
e1t_var.long_name = 'e1t'
e1t_var[:] = e1t

e1v_var = ncd.createVariable('e1v', 'float64', ('t', 'y','x'))
e1v_var.units = 'e1v'
e1v_var.long_name = 'e1v'
e1v_var[:] = e1v

e2t_var = ncd.createVariable('e2t', 'float64', ('t', 'y','x'))
e2t_var.units = 'e2t'
e2t_var.long_name = 'e2t'
e2t_var[:] = e2t

e2u_var = ncd.createVariable('e2u', 'float64', ('t', 'y','x'))
e2u_var.units = 'e2u'
e2u_var.long_name = 'e2u'
e2u_var[:] = e2u

In [117]:
nc_tools.check_dataset_attrs(ncd)
ncd.close()

Missing value for dataset attribute: references
